export const MESSAGE_REQUIRED = '必ず入力してください';
export const MESSAGE_IS_INT = '整数を入力してください';
export const MESSAGE_IS_STRING = '文字列を入力してください';
export const MESSAGE_IS_NUMERIC = '数値を入力してください';
export const MESSAGE_IS_OC = 'STJJのオブジェクトクラスとして利用可能なものを入力してください';
export const MESSAGE_IS_MAINTYPE = 'STJJのメインタイプとして利用可能なものを入力してください';
export const MESSAGE_IS_ARRAY = '配列を入力してください';
export const MESSAGE_IS_ARRAY_OF_STRING = '配列の要素は文字列を入力してください';
export const MESSAGE_IS_BOOLEAN = 'bool値を入力してください';
export const MESSAGE_NG_USERNAME = 'そのユーザー名は利用できません。他のユーザー名で登録してください';
export const MESSAGE_MALFORMED_USERNAME = 'ユーザー名は半角英数字、半角アンダーバーで登録してください';
export const MESSAGE_USERNAME_ALREADY_USED = '既に利用されているユーザー名です';
export const MESSAGE_IS_EMAIL = '不正なメールアドレス形式です';
export const MESSAGE_EMAIL_ALREADY_USED = '既に利用されているメールアドレスです';
export const MESSAGE_PASSWORD_LENGTH_MIN = 'パスワードは8文字以上で登録してください';
export const MESSAGE_PASSWORD_USE_NUM = 'パスワードには半角数字を最低1文字入れてください';
export const MESSAGE_PASSWORD_USE_ALPHABET = 'パスワードには半角英字を最低1文字入れてください';

export const SALT_ROUNDS = 10;

export const ERROR_AUTHENTICATION_FAILED = new Error(); // 正常系で認証失敗した場合のエラー用オブジェクト

export const NG_USERNAMES = [
  "index",
  "home",
  "top",
  "help",
  "about",
  "security",
  "contact",
  "connect",
  "support",
  "faq",
  "form",
  "mail",
  "update",
  "mobile",
  "phone",
  "portal",
  "facebook",
  "twitter",
  "Instagram",
  "LinckedIn",
  "GitHub",
  "tour",
  "tutorial",
  "navigation",
  "navi",
  "manual",
  "doc",
  "digest",
  "company",
  "store",
  "shop",
  "topic",
  "news",
  "information",
  "info",
  "howto",
  "pr",
  "press",
  "release",
  "sitemap",
  "plan",
  "price",
  "business",
  "premium",
  "member",
  "term",
  "privacy",
  "rule",
  "inquiry",
  "legal",
  "policy",
  "ToS",
  "Term-of-Service",
  "ToS4Paid",
  "env",
  "icon",
  "image",
  "img",
  "photo",
  "css",
  "stylesheet",
  "style",
  "script",
  "src",
  "js",
  "javascript",
  "dist",
  "asset",
  "source",
  "static",
  "file",
  "flash",
  "swf",
  "xml",
  "json",
  "sag",
  "cgi",
  "account",
  "user",
  "item",
  "entry",
  "article",
  "page",
  "archive",
  "tag",
  "category",
  "event",
  "contest",
  "word",
  "product",
  "project",
  "download",
  "video",
  "blog",
  "diary",
  "site",
  "popular",
  "i",
  "my",
  "me",
  "owner",
  "profile",
  "self",
  "old",
  "first",
  "last",
  "start",
  "end",
  "special",
  "design",
  "theme",
  "purpose",
  "book",
  "read",
  "organization",
  "community",
  "group",
  "all",
  "test",
  "status",
  "state",
  "search",
  "explore",
  "share",
  "feature",
  "upload",
  "rss",
  "atom",
  "widget",
  "api",
  "wiki",
  "bookmark",
  "captcha",
  "comment",
  "jump",
  "ranking",
  "setting",
  "config",
  "tool",
  "connect",
  "notify",
  "recent",
  "report",
  "system",
  "sys",
  "message",
  "msg",
  "log",
  "analysis",
  "query",
  "call",
  "calendar",
  "friend",
  "graph",
  "watch",
  "cart",
  "activity",
  "activate",
  "username",
  "password",
  "auth",
  "session",
  "register",
  "login",
  "logout",
  "signup",
  "signin",
  "signout",
  "forget",
  "forgot",
  "admin",
  "administrator",
  "root",
  "secure",
  "get",
  "show",
  "create",
  "edit",
  "update",
  "post",
  "destroy",
  "delete",
  "remove",
  "reset",
  "error",
  "new",
  "dashboard",
  "recruit",
  "join",
  "offer",
  "career",
  "corp",
  "cgi-bin",
  "server-status",
  "balancer-manager",
  "ldap-status",
  "server-info",
  "svn",
];
